### ISSUE TITLE
Improve mass processing

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/column_classifier_tool#4]
- [x] JSON output should be read to only process unprocessed files (this makes stopping + resuming possible)
- [x] Decrease processing time
- [x] Check for memory leaks

**Comment by mikegerber** [comment]
I've processed 203 test images with the latest changes and in one call - memory usage stayed at ~ 1GB RSS (manually checked with `htop`).

In the changes I 
1. create only 1 TensorFlow sessions and load the models only once
2. also removed all `del` statements and `gc.collect()` calls as they seemed unnecessary. If we still experience memory leaks anywhere we are going to have to revisit this and "do it smarter".

**Comment by mikegerber** [comment]
Using the same 203 test images:

~~~
% sbb_column_classifier test-images/*.tif --model ~/devel/qurator-data/eynollah
2022-02-10 13:09:31 sbb_column_classifier DEBUG    Loading model model_scale_classifier.h5...
2022-02-10 13:09:38 sbb_column_classifier DEBUG    Loading model done.
2022-02-10 13:09:38 sbb_column_classifier DEBUG    Loading model model_page_mixed_best.h5...
2022-02-10 13:09:45 sbb_column_classifier DEBUG    Loading model done.
2022-02-10 13:09:45 sbb_column_classifier DEBUG    Running for test-images/100.tif...
The document image 'test-images/100.tif' has 1 column!
[...]
2022-02-10 13:20:57 sbb_column_classifier DEBUG    Running for test-images/OCR-D-IMG_00000031.tif...
The document image 'test-images/OCR-D-IMG_00000031.tif' has 1 column!
2022-02-10 13:21:01 sbb_column_classifier DEBUG    Run done.
~~~

So this took 11m30s to process 203 images (on my dual core laptop, and on CPU), this is 3.3s/image. Model loading took 14s and this is now done only once per call, i.e. once for all 203 images.

**Comment by cneud** [comment]
> this took 11m30s to process 203 images

Nice, that sounds very promising for throughput!

**Comment by mikegerber** [comment]
e4e2016 now checks if a file was already processed.

**Comment by mikegerber** [comment]
Latest version now reads and writes its results to a JSON file. It skips already processed input files, so this enables resuming.

**Comment by mikegerber** [comment]
The JSON output was too resource-consuming to read/write, so I switched to SQLite (using the small peewee ORM library).
